language: node_js
node_js:
  - "8.9.1"

# Cache the node_modules directory
cache:
  directories:
    - node_modules

# Require Docker services
services:
  - docker

env:
  global:
  - NAME=mavis

before_install:
  # Install certbot to generate certs
  # - wget https://dl.eff.org/certbot-auto
  # - chmod a+x certbot-auto


install:
  - npm install

before_script:
  # - npm run lint

script:
  # Build the Docker image 
  - docker build -t $NAME src/.

  # Run the Docker conatiner 
  - docker run -d --name $NAME -e HOST=0.0.0.0 -p "3000:443" $NAME

  # Sleep for a bit to allow time to start up
  - sleep 30

  # Health check
  - curl --insecure -X GET https://0.0.0.0:3000/api/v1/healthcheck

  # Run tests
  - npm run test

after_failure:
  - docker ps -a
  - docker logs $NAME

after_success:
  - docker tag $NAME $DOCKER_REPO/$NAME
  - docker push $DOCKER_REPO/$NAME

notifications:
  email: false
  
# before_deploy:
#   # Zip src dir for deployment otherwise it will zip the parent project with test stuff and deploy that
#   - cd src
#   - zip -r mavis.zip *

# deploy:
#   provider: elasticbeanstalk
#   access_key_id: AKIAI5KN4FKDSFLZXAGQ
#   secret_access_key:
#     secure: edgsdjloM6BYvKfceVy20E+VrUcD3YXsMWPw04rUYcv8hkQ4nZvN5yHw6cFrIY1DABvv9WaGR57E/P2QgU1sqVcOz1dwWf3N9KsCDlgU+aNKQ5nntPLt3p2sjtEJlHK05XA/smuiz+7pt5z+YRo7adkJG7kBnuRh5BmBiY2oWYEQfNj3tJ6+g8D6CdZFJMoff4TX+4fR+xkd1qrUoK40liXe2qMqVuC7kFge75zdFiWGzHx7vfixaeaxQrskq0eb/Cc6iVMMzFs67HqxiSyZjLiCKSql3zjQFMHku5L84ZgsIXIYOnLx2R8WGhxyyIlKZhiLxaJRVESY6k9zCpvNc11prkV/TDWOivlGLyODjx8a4sByOxNogqAeBAoLOjKsq88Veiyn2d2Ehz0pZibOhPMGVXTrjLQzGIBdiJj8zidKNXf4HWd4o+4Wbj3l2nndoSeutVFf/Ba9AApk1ezo0yhIgLNbWNSsmnRFwEVliJK1SQXbJIhq/boZwMBq610MU72bSF4x2vz0R2olB24Pe3bedVKbp+toZtVzXimrFsVllidYce9JbPTt3cU/g3c1sNAOpcYMvrN5URt/UmlJMku9CZJ2DPHD6I+alylRY41wVSaJQUDta69FHqGSgljg4nO7XFqqxeQ0Sw4+NHJkDWsD3n+8GoboMyZmhRmTOgI=
#   # region: Central # Beanstalk only works on us-east-1 for some reason
#   app: mavis
#   env: Mavis-env
#   bucket_name: ${AWS_S3_BUCKET_NAME}
#   zip_file: 'mavis.zip'
#   skip_cleanup: true
#   on:
#     repo: danielnguyen/mavis-bot