language: node_js
node_js:
  - "8.9.1"

# Cache the node_modules directory
cache:
  directories:
    - node_modules

# Require Docker services
services:
  - docker

env:
  global:
  - Name=mavis

install:
  - npm install

before_script:
  # - npm run lint

script:
  - npm run test

after_failure:
  - docker ps -a
  - docker logs $NAME

notifications:
  email: false

deploy:
  provider: elasticbeanstalk
  access_key_id: ${AWS_ACCESS_KEY_ID}
  secret_access_key:
    secure: qasZI2bKLwmeFqvcbGVpUsHfQIlab3hTLkUBeaY03Cmlfh15MpxiMANbKy0EIe/HyZ+wLpREM5DYs9DYG47IvD/cNl6AwIlJNBGUpjVT2bTJAIdp+hRpLdFaLtivnqnNAmfGRANhfx+Ju+Ei9FhkYxcXmpToMxC6uvzw4mhTdFebg6ZbiR9iuURhiYYQ+JSDvFwUome0lT3yw4hNXSHjQed2ICuOavt7uhI77s3aZeyxOEBTDXraDnl6iqbqv29uR3jQpOP/oJNN9O3QXN1OuGcFxlWqu4ZodFXmgVyGq/PSQprUDpk/YUDWK5/2TP1kR52um1Xd5E94+H97PggIYbY5/jDByCpi34oWPspqsyVL9QCke7jYNGUQhdZe1LUyVWdawDpLBVOYhLSpyy/TpehL99K/MRT06LCxZO9wzblTUBobSX/LpwISH9ZP4yvcaZcrPFBZrx16WPd1y0LLksZC5gJgs7EFKe5RQUl7eews352PmrN5rk1mWiJnYmwz/Nqp6Ndc073OeIREiKWTaUoFx2Xyz8+Ueo19PnB7OB+W6dgYIZysSwJ40GfPVLcm51TYkftTE9REDSlfwQyp0ru51w6fXMop0NhwtfACY+HLPzqfxB291Msg835/Rav79Tp6hJhpbpR82OhkgxDdvoYeGcWtpMwwGQBxcLrgkUU=
  # region: Central
  app: Mavis
  env: Mavis-env
  bucket_name: ${AWS_S3_BUCKET_NAME}
  on:
    repo: danielnguyen/mavis-bot
    # branch: prod