version: '3'
services:
  mavis:
    build: ./src
    ports:
     - "3000:3000"
    networks:
      - front-tier
    env_file:
      - ./src/.env
  redis:
    image: "redis:alpine"
    container_name: redis
    ports: 
      - "6379:6379"
    networks:
      - back-tier

networks:
  front-tier:
  back-tier: