# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

defaults: &defaults
  working_directory: ~/app
  docker:
    - image: node:8-alpine


jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      # Download and cache dependencies
      # - restore_cache:
      #     keys:
      #     - v1-dependencies-{{ checksum "package.json" }}
      #     # fallback to using the latest cache if no exact match is found
      #     - v1-dependencies-

      - run: npm install

      # - save_cache:
      #     paths:
      #       - node_modules
      #     key: v1-dependencies-{{ checksum "package.json" }}
        
  test:
    <<: *defaults
    steps:
      - checkout
      # - restore_cache:
      #     key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: test
          command: npm run test

  deploy:
    working_directory: ~/app
    docker:
      - image: coxauto/aws-ebcli
    steps:
      - checkout
      # - restore_cache:
      #     key: dependency-cache-{{ checksum "yarn.lock" }}
      - run: 
          name: deploy app to EB
          command: eb deploy --profile default --timeout 45

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      # - test:
      #     requires:
      #       - build
      # - hold:
      #     type: approval
      #     requires:
      #       - test
      #       - lint
      - deploy:
          requires:
            - build
            # - hold